"""Simple auto-update helper for Windows builds.

This module checks the latest release on GitHub and, when a newer version is
available, offers to download and run the installer.  The actual repository is
read from the ``GITHUB_REPO`` environment variable.  If it is not provided the
default ``"owner/TextGameScript"`` is used and should be replaced during the
build process.

The function is intentionally light-weight and uses only the Python standard
library so it can run inside the PyInstaller executables generated by the
workflow.
"""

from __future__ import annotations

import json
import os
import platform
import subprocess
import tempfile
import urllib.request
from tkinter import messagebox


GITHUB_REPO = os.environ.get("GITHUB_REPO", "owner/TextGameScript")


def _ver_tuple(ver: str) -> tuple[int, ...]:
    return tuple(int(p) for p in ver.split(".") if p.isdigit())


def check_for_update(app_name: str, current_version: str, installer_name: str, *, parent=None) -> None:
    """Check GitHub for a newer release and optionally run the installer.

    Parameters
    ----------
    app_name: str
        Display name of the application.
    current_version: str
        Version string of the running application.
    installer_name: str
        Expected asset name of the installer in the GitHub release.
    parent: tkinter widget, optional
        Parent widget for message boxes.
    """

    if platform.system() != "Windows":
        return

    try:
        url = f"https://api.github.com/repos/{GITHUB_REPO}/releases/latest"
        with urllib.request.urlopen(url, timeout=5) as resp:
            data = json.load(resp)
        tag = data.get("tag_name", "")
        latest = tag[1:] if tag.startswith("v") else tag
        if _ver_tuple(latest) <= _ver_tuple(current_version):
            return

        msg = f"{app_name} {latest} 버전이 있습니다. 지금 업데이트할까요?"
        if not messagebox.askyesno("업데이트", msg, parent=parent):
            return

        asset_url = None
        for asset in data.get("assets", []):
            if asset.get("name") == installer_name:
                asset_url = asset.get("browser_download_url")
                break
        if not asset_url:
            return

        tmp = tempfile.NamedTemporaryFile(delete=False, suffix=".exe")
        tmp.close()
        urllib.request.urlretrieve(asset_url, tmp.name)
        subprocess.Popen([tmp.name, "/VERYSILENT", "/NORESTART"])
        messagebox.showinfo("업데이트", "설치 프로그램이 실행되었습니다.", parent=parent)
    except Exception:
        # 업데이트 실패는 조용히 무시
        pass


__all__ = ["check_for_update"]

